Django_Portfolio_app/homepage/urls.py
from django.urls import path
from homepage import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

Django_Portfolio_app/portfoilio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('all-projects/', include('projects.urls', namespace='all-projects')),
    path('', include('homepage.urls', namespace='home'))
]

Django_Portfolio_app/projects/urls.py
from django.urls import path
from projects import views

app_name = 'projects'

urlpatterns = [
    path('', views.all_projects, name='all_projects'),
    path('<int:pk>', views.projects_detail, name='project_detail'),
]


# # Class Based View
# urlpatterns = [
#     path('', views.ExampleClassView.as_view())
# ]

Django_Portfolio_app/homepage/models.py
from django.db import models

# Create your models here.

Django_Portfolio_app/projects/models.py
from django.db import models

# Create your models here.


class Projects(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=20)
    image = models.CharField(max_length=100)

Django_Portfolio_app/homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'homepage/index.html')

Django_Portfolio_app/projects/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View
from projects.models import Projects

# Create your views here.


def all_projects(request):
    # Query the db to return all project objects.
    projects = Projects.objects.all()
    context = {'projects': projects}
    return render(request, 'projects/all_projects.html', context=context)


def projects_detail(request, pk):
    project = Projects.objects.get(pk=pk)
    context = {'project': project}
    return render(request, 'projects/project.html', context)



# class ExampleClassView(View):
#     """ Example Class Based View """
#     html='projects/index.html'
#     def get(self, request):
#         return render(request, self.html)

Django_Portfolio_app/homepage/templates/homepage/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'projects:all_projects' %}">View All Projects</a>
</body>
</html>

Django_Portfolio_app/projects/templates/projects/all_projects.html
{% extends 'projects/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1>All Projects</h1>

    {% for project in projects %}
    <div class="card" style="width: 18rem; padding: 20px; display: inline-block;">
        <img class="card-img-top" style="height: 150px; width: auto" src="{% static project.image %}"
            alt="Project image" />
        <div class="card-body">
            <h5>{{project.title}}</h5>
            <p>{{project.description}}</p>
            <p>Technology: {{project.technology}}</p>
            <a href="{% url 'projects:project_detail' project.pk %}" class="btn btn-primary">Project detail</a>
        </div>
    </div>
    {% endfor %}

</div>
{% endblock %}

Django_Portfolio_app/projects/templates/projects/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>

<body>
    {% block content %}

    {% endblock %}
</body>

</html>

Django_Portfolio_app/projects/templates/projects/project.html
{% extends 'projects/base.html' %}
{% load static %}

{% block title %}Project {{project.pk}} {% endblock %}

{% block content %}
<div class="container">
    <h1>Project Detail Page</h1>
    <img class="card-img-top" style="height: 450px; width: auto" src="{% static project.image %}" alt="Project image" />
    <h5>{{ project.title }}</h5>
    <p>{{ project.description }}</p>
    <p>Technology: {{ project.technology }}</p>
    <a href="{% url 'projects:all_projects' %}" class="btn btn-primary">Go Back</a>
</div>
{% endblock %}